[theme]

# Primary accent for interactive elements
primaryColor = '#F63366'

# Background color for the main content area
backgroundColor = '#fff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F0F2F6'

# Color used for almost all text - you can use #fff shortcode for white
textColor = '#262730'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"